name: Build Aily Blockly Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. 下载代码到云电脑
      uses: actions/checkout@v4

    - name: 2. 安装 Node.js 环境
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 3. 安装前端界面的依赖包
      run: npm install

    - name: 4. 安装底层核心的依赖包
      run: |
        cd electron
        npm install

    - name: 5. 自动解压并配置编译器组件
      shell: cmd
      run: |
        xcopy /E /I /Y child\windows\* child\
        cd child
        7z x node-v22*-win-x64.7z
        ren node-v22*-win-x64 node
        7z x aily-builder-*.7z
        ren aily-builder-* aily-builder

    - name: 6. 开始打包成 .exe 安装程序
      run: npm run build

    - name: 7. 将打包好的软件传回网页供你下载
      uses: actions/upload-artifact@v4
      with:
        name: Aily-Blockly-Windows-App
        path: dist/aily-blockly/
